# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [2]:
import numpy.random as npr
npr.seed(42)
with open("simple_data2.txt","+a") as f:
    a=npr.random((100,1))
    for i in a:
        f.write(str(i))

df=pd.DataFrame(a)
df.to_csv("simple_data.txt",index=False)

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [3]:
m=npr.random((5,5))
print(m)
df=pd.DataFrame(m)
df.to_csv("data.txt",index=False)

[[0.03142919 0.63641041 0.31435598 0.50857069 0.90756647]
 [0.24929223 0.41038292 0.75555114 0.22879817 0.07697991]
 [0.28975145 0.16122129 0.92969765 0.80812038 0.63340376]
 [0.87146059 0.80367208 0.18657006 0.892559   0.53934224]
 [0.80744016 0.8960913  0.31800347 0.11005192 0.22793516]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [4]:
import csv
with open('data.txt','r') as p:
    with open('data.csv','w') as n:
        writer=csv.writer(n)
        for row in p:
            writer.writerow(row.split())
        



4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [39]:
with open('credit_card.dat','r') as data:
    for row in data:
      #print(row)
      row=row[:-5]
      p=[row[i:i+6]for i in range(0,len(row),6)]
      #print(p)
      ii=[chr(int(x,2)) for x in p]
      print(ii)



'''
df=pd.read_csv('credit_card.dat',header=None)
for row in df:
  a=str(row)
  print(type(a))
  #row=row[:-4]
  #p=[a[i:i+n] for i in range(0, len(a), 6)]
  #print(p)


df
'''




['7', '6', '4', '8', ' ', '5', '6', '7', '3', ' ', '3', '7', '7', '5', ' ', '2', '2', '7', '1']
['3', '2', '5', '7', ' ', '8', '2', '4', '7', ' ', '3', '3', '5', '4', ' ', '2', '2', '6', '6']
['2', '7', '2', '2', ' ', '0', '0', '0', '1', ' ', '4', '0', '1', '1', ' ', '6', '6', '5', '2']
['0', '6', '6', '1', ' ', '3', '0', '6', '3', ' ', '3', '7', '4', '2', ' ', '3', '1', '5', '0']
['0', '4', '3', '2', ' ', '1', '6', '0', '8', ' ', '1', '4', '6', '2', ' ', '4', '7', '4', '2']
['5', '8', '2', '7', ' ', '2', '0', '2', '7', ' ', '8', '7', '8', '5', ' ', '7', '3', '0', '3']
['5', '7', '7', '4', ' ', '8', '5', '2', '8', ' ', '2', '0', '8', '7', ' ', '1', '1', '1', '7']
['8', '1', '4', '0', ' ', '1', '2', '1', '0', ' ', '6', '3', '5', '2', ' ', '2', '8', '4', '5']
['5', '7', '6', '4', ' ', '1', '1', '3', '3', ' ', '7', '3', '0', '1', ' ', '7', '1', '0', '0']
['6', '4', '5', '6', ' ', '1', '7', '3', '7', ' ', '4', '1', '2', '6', ' ', '6', '7', '2', '6']
['1', '2', '2', '8', ' ', '8', '6', '3',

"\ndf=pd.read_csv('credit_card.dat',header=None)\nfor row in df:\n  a=str(row)\n  print(type(a))\n  #row=row[:-4]\n  #p=[a[i:i+n] for i in range(0, len(a), 6)]\n  #print(p)\n\n\ndf\n"

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

In [49]:
import json
data=json.load(open('user_data.json'))
# Filter dictionary where name is 'Bob'
filtered_dict = [item for item in data if item.get("CreditCardType") == "American Express"]
print(filtered_dict)
df=pd.DataFrame(filtered_dict)
df.to_csv('amex.csv',index=False)
'''
with open('amex.csv','w') as data:
    with open('amex.csv','w') as n:
        writer=csv.writer(n)
        for row in filtered_dict:
            writer.writerow(row.split())
'''

[{'ID': '2', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com', 'FirstNameLastName': 'Clint Thorpe', 'CreditCard': '7083-8766-0251-2345', 'CreditCardType': 'American Express'}, {'ID': '12', 'JobTitle': 'Retail Trainee', 'EmailAddress': 'Phillip_Carpenter9505@famism.biz', 'FirstNameLastName': 'Phillip Carpenter', 'CreditCard': '3657-0088-0820-5247', 'CreditCardType': 'American Express'}, {'ID': '28', 'JobTitle': 'Project Manager', 'EmailAddress': 'Russel_Graves1378@extex.org', 'FirstNameLastName': 'Russel Graves', 'CreditCard': '6718-4818-8011-6024', 'CreditCardType': 'American Express'}, {'ID': '39', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Leanne_Newton1268@typill.biz', 'FirstNameLastName': 'Leanne Newton', 'CreditCard': '5438-0816-4166-4847', 'CreditCardType': 'American Express'}, {'ID': '57', 'JobTitle': 'Budget Analyst', 'EmailAddress': 'Tony_Giles1960@iatim.tech', 'FirstNameLastName': 'Tony Giles', 'CreditCard': '8130-3425-7573-7745', 'CreditCard

"\nwith open('amex.csv','w') as data:\n    with open('amex.csv','w') as n:\n        writer=csv.writer(n)\n        for row in filtered_dict:\n            writer.writerow(row.split())\n"

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the histogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.