# OSEMN Exercises

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [26]:
import numpy.random as npr
npr.seed(42)
with open("simple_data2.txt","+a") as f:
    a=npr.random((100,1))
    for i in a:
        f.write(str(i))

df=pd.DataFrame(a)
df.to_csv("simple_data.txt",index=False)

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [34]:
m=npr.random((5,5))
print(m)
df=pd.DataFrame(m)
df.to_csv("data.txt",index=False)

[[0.72821635 0.36778313 0.63230583 0.63352971 0.53577468]
 [0.09028977 0.8353025  0.32078006 0.18651851 0.04077514]
 [0.59089294 0.67756436 0.01658783 0.51209306 0.22649578]
 [0.64517279 0.17436643 0.69093774 0.38673535 0.93672999]
 [0.13752094 0.34106635 0.11347352 0.92469362 0.87733935]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [36]:
import csv
with open('data.txt','r') as p:
    with open('data.csv','w') as n:
        writer=csv.writer(n)
        for row in p:
            writer.writerow(row.split())
        



4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.