# OSEMN Exercises

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [26]:
import numpy.random as npr
npr.seed(42)
with open("simple_data2.txt","+a") as f:
    a=npr.random((100,1))
    for i in a:
        f.write(str(i))

df=pd.DataFrame(a)
df.to_csv("simple_data.txt",index=False)

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [34]:
m=npr.random((5,5))
print(m)
df=pd.DataFrame(m)
df.to_csv("data.txt",index=False)

[[0.72821635 0.36778313 0.63230583 0.63352971 0.53577468]
 [0.09028977 0.8353025  0.32078006 0.18651851 0.04077514]
 [0.59089294 0.67756436 0.01658783 0.51209306 0.22649578]
 [0.64517279 0.17436643 0.69093774 0.38673535 0.93672999]
 [0.13752094 0.34106635 0.11347352 0.92469362 0.87733935]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [36]:
import csv
with open('data.txt','r') as p:
    with open('data.csv','w') as n:
        writer=csv.writer(n)
        for row in p:
            writer.writerow(row.split())
        



4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [49]:
with open('credit_card.dat','r') as data:
    max=6


df=pd.read_csv('credit_card.dat',header=None)
for row in df:
  print(len(str(row)))
df






1


0
0   1101101101001110001000001101011101101101111100...
1   1100111100101101011101111000001110001100101101...
2   1100101101111100101100101000001100001100001100...
3   1100001101101111101101101100011000001100111100...
4   1100001101001100111100101000001100011101101100...
5   1101011110001100101101111000001100101100001100...
6   1101011101111101111101001000001110001101011100...
7   1110001100011101001100001000001100011100101100...
8   1101011101111101101101001000001100011100011100...
9   1101101101001101011101101000001100011101111100...
10  1100011100101100101110001000001110001101101100...
11  1101111100001101011100011000001100001100011101...
12  1100001101101100011110001000001100111101011110...
13  1100011101011101001101011000001101011101001101...
14  1101101101111100111101011000001100111100011100...
15  1101111100101110001101111000001101011100001100...
16  1101111100001100111100111000001100101101101100...
17  1100101101011101101110001000001101011100101101...
18  1100011101101110001101001000001100101100101101...
19  1100001101101101111100101000001100101101011101...
20  1101101100111100111100101000001110001100111101...
21  1100011110001100011100111000001100111100111101...
22  1100101101001101111101111000001101101101001101...
23  1101011101011100011100101000001100111101011100...
24  1100111100001110001100111000001101111110001110...
25  1101001101011100101100011000001101011100011101...
26  1101111101011101101100111000001100111101101101...
27  1110001100111100101101001000001100101101101101...
28  1100001101011101101101011000001100101101011100...
29  1101011100011100001101111000001101011101011100...
30  1100101101001101101100101000001100011110001100...
31  1100101101111110001110001000001100001101101100...
32  1101011110001101011100011000001101011110001101...
33  1100001101101101111100001000001100011100001100...
34  1101011110001101111101001000001101011101011100...
35  1100101110001100001101011000001101011101001100...
36  1101011100001110001100111000001110001101001100...
37  1100011100001101111101101000001100011101001101...
38  1110001101001101001100001000001101001110001100...
39  1101001101111101011110001000001101101100011101...
40  1101111101011110001101101000001100001101101101...
41  1100101101011101001101001000001100011100101101...
42  1100111101001101111101001000001101011100001100...
43  1100011101001100011100001000001100001100101101...
44  1101111100111100011101011000001101001101001101...
45  1100001100101100101101001000001101111101111101...
46  1100001100011101111100001000001100101101111100...
47  1100101100001100001101101000001100101101001100...
48  1110001100011101001100101000001101001100001101...
49  1100111100001100101101101000001101111100111110...
50                                               1010

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.